### ISSUE TITLE
Clinical Procedure Templates

### ISSUE THREAD

**Issue by fibersoft** [earthians/marley#105]
Hello team frappe .... there is an issue in ITEM tab of clinical procedure template. ERP Next does not search item (product, service) in clinical procedure item tab that we have created already. So please look into this in healthcare domain completely.

Thanks

**Comment by akashkrishna619** [comment]
When you save the Clinical Procedure Template, system will create the Item and link to the template.

**Comment by akashkrishna619** [comment]
Thanks for reporting this, Item link field is read_only - will enable this and push a fix

**Comment by fibersoft** [comment]
@akashkrishna619 you are right (When you save the Clinical Procedure Template, system will create the Item and link to the template)

But my concern about the item , we already have created, that is not searchable in CLINICAL PROCEDURE TEMPLATE. There are also some other fields in different forms of healthcare domain in which ITEM is not searchable. So please do some testing. The item field should fetch item as practitioner or patient fields fetch their own data.

Thanks

**Comment by ChillarAnand** [comment]
This issue is fixed as part of https://github.com/frappe/healthcare/pull/107. 

Let us know if you are still facing it. @fibersoft

**Comment by ChillarAnand** [comment]
Closing this issue. Feel free to re-open if the issue persists.
