### ISSUE TITLE
New Clinical Procedure Template (ISSUES)

### ISSUE THREAD

**Issue by fibersoft** [earthians/marley#108]
Hello team frappe- ERPNext
Hope you are all fine. 

This is informed you that in Healthcare domain, the item we already have created, is not searchable in multiple documents  especially NEW CLINICAL PROCEDURE TEMPLATE. I have informed already to frappe team but issue has not been overcome.  Please have a test of complete healthcare domain to search item in different forms.

I hope this time the team will work on this.

Thanks

**Comment by akashkrishna619** [comment]
Hi, this [pr](https://github.com/frappe/healthcare/pull/107) should resolve the issues mentioned above. we'll be fixing the failing tests and get it merged
