### ISSUE TITLE
Missing Options on Sales Invoice with Healthcare App in erpnext v14

### ISSUE THREAD

**Issue by osama1998H** [earthians/marley#126]
### hi there I have a problem with getting the patient fees in the sales invoice in v14
**but it works correctly in version 13 and nightly like this picture**

![photo_2022-08-14_10-40-59](https://user-images.githubusercontent.com/42488643/184527737-91673c3e-93fe-4d6b-a4d3-53727add74b6.jpg)

**These options are missing in version 14 with healthcare like this image**

![photo_2022-08-14_10-41-00](https://user-images.githubusercontent.com/42488643/184527695-2eb70333-bc6f-4362-9e8a-a115b1749c80.jpg)

**_and also not found in erpnext documentation_** 

![photo_2022-08-14_10-40-59 (2)](https://user-images.githubusercontent.com/42488643/184527760-134c0e45-e011-416b-81ba-6d8e2fc85501.jpg)

**Comment by ChillarAnand** [comment]
This is fixed as part of https://github.com/frappe/health/pull/127.

Feel free to re-open if you are still facing the issue.
