### ISSUE TITLE
can i show here a calendar view fetched from patient appiontments ?

### ISSUE THREAD

**Issue by Abdo2021-a** [earthians/marley#129]
![1](https://user-images.githubusercontent.com/82307815/184996444-f198b0e0-444c-4d5a-bdae-2d8e2f22a6fc.png)

**Comment by ChillarAnand** [comment]
Users can go to `Patient Appointment` and click on calendar view to see it.

You can use https://discuss.erpnext.com/ to get fast response to general queries.
