### ISSUE TITLE
Merge latest develop to brnach hsr-insurance-wip as we want to test in live

### ISSUE THREAD

**Issue by chechani** [earthians/marley#138]
We would like to integrate insurance with the claim book application and want to try out the insurance branch of health, so any changes in the developed branch if merged to this branch will help a lot.

Thanks in advance

**Comment by ChillarAnand** [comment]
@chechani Insurance branch has some bugs that are yet to be fixed. Once they are fixed, we will merge it to main branch.

If you want to try out locally, you can pull changes from this branch and test it out.

https://github.com/frappe/health/pull/66

If you need any other information, let us know.
