### ISSUE TITLE
Remove Experimental flag

### ISSUE THREAD

**Issue by ernestoruiz89** [earthians/marley#146]
The product is robust enough to remove the experimental flag, meets the needs of a clinic and is functional.

![image](https://user-images.githubusercontent.com/1592496/196970462-839b843a-7b35-433d-875a-10de57cf1281.png)

**Comment by ChillarAnand** [comment]
Good point @ernestoruiz89. Frappe Health is already being used for [many hospitals](https://discuss.erpnext.com/t/list-of-hospital-clinics-using-erpnext-healthcare/79721/2?u=chillaranand) through out the world.
