### ISSUE TITLE
Healthcare: Healthcare Practitioner is not searchable by practitioner_name in Patient Encounter

### ISSUE THREAD

**Issue by mujeerhashmi** [earthians/marley#149]
## Description of the issue
Healthcare Practitioner is not searchable by practitioner_name in Patient Encounter

**Comment by mujeerhashmi** [comment]
@akurungadam @ruchamahabal Need your attention to this issue.

**Comment by akashkrishna619** [comment]
@mujeerhashmi closing this as it is not reproducible in the latest version
