### ISSUE TITLE
[BUG]When using other language except English, will meet error: Could not find Parent Item Group: All Item Groups

### ISSUE THREAD

**Issue by mojerro** [earthians/marley#161]
same as #30 . I'm trying to install ERPNext in Chinese, and I met an error shows `frappe.exceptions.LinkValidationError: Could not find Parent Item Group: All Item Groups`.

I found items saved in the database are translated into Chinese and the health app trying to find the item in English. Is there any way to install it successfully with out changing the DB directly.

**Comment by akurungadam** [comment]
Please check this [solution](https://discuss.erpnext.com/t/update-error-in-frappe-get-single-domain-settings-save/30198/5) on the forum, thanks!

**Comment by akurungadam** [comment]
Not quite related to healthcare, closing this for now.
