### ISSUE TITLE
Email notification not getting delivered to patient email

### ISSUE THREAD

**Issue by deepakc21** [earthians/marley#168]
Issue: Email notification not getting delivered to patient email

Steps to reproduce the bug:

1. Click on 'New Notification' in the "Notification List".
2. Enter 'Test Template' and 'Patient' information.

Actual result: No email sent to patient's email id.
Notification settings:
![health](https://user-images.githubusercontent.com/97949896/205638322-f7df4959-a6a5-4252-9bb0-a8d2dfe71256.png)

Error log:
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 159, in execute_job
    method(**kwargs)
      site = 'tatiportal.frappe.cloud'
      method = <function send_mail at 0x7f07a71ebd90>
      event = None
      job_name = '<function send_mail at 0x7ff7105cb520>'
      kwargs = {'email_queue_name': '3c37663500', 'is_background_task': True}
      user = 'Administrator'
      is_async = True
      retry = 0
      method_name = 'send_mail'
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 184, in send_mail
    record.send(is_background_task=is_background_task, smtp_server_instance=smtp_server_instance)
      email_queue_name = '3c37663500'
      is_background_task = True
      smtp_server_instance = None
      record = <EmailQueue: 3c37663500>
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 129, in send
    with SendMailContext(self, is_background_task, smtp_server_instance) as ctx:
      self = <EmailQueue: 3c37663500>
      is_background_task = True
      smtp_server_instance = None
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 196, in __init__
    self.email_account_doc = queue_doc.get_email_account()
      self = <frappe.email.doctype.email_queue.email_queue.SendMailContext object at 0x7f07a70b0430>
      queue_doc = <EmailQueue: 3c37663500>
      is_background_task = True
      smtp_server_instance = None
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 105, in get_email_account
    return frappe.get_cached_doc("Email Account", self.email_account)
      self = <EmailQueue: 3c37663500>
  File "apps/frappe/frappe/__init__.py", line 1083, in get_cached_doc
    doc = get_doc(*args, **kwargs)
      args = ('Email Account', 'admin')
      kwargs = {}
      _respond = <function get_cached_doc.<locals>._respond at 0x7f07a705aef0>
      doc = None
      key = 'Email Account::admin'
  File "apps/frappe/frappe/__init__.py", line 1176, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
      args = ('Email Account', 'admin')
      kwargs = {}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
      args = ('Email Account', 'admin')
      kwargs = {}
      doctype = 'Email Account'
      controller = <class 'frappe.email.doctype.email_account.email_account.EmailAccount'>
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
      self = <EmailAccount: admin>
      args = ('Email Account', 'admin')
      kwargs = {}
      __class__ = <class 'frappe.model.document.Document'>
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
      self = <EmailAccount: admin>
      d = None
      __class__ = <class 'frappe.model.document.Document'>
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
      msg = 'Email Account admin not found'
      exc = <class 'frappe.exceptions.DoesNotExistError'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      sys = <module 'sys' (built-in)>
      out = {'message': 'Email Account admin not found', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1}
      _strip_html_tags = <functools._lru_cache_wrapper object at 0x7f07a6f28250>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x7f07a7100dc0>
      inspect = <module 'inspect' from '/usr/lib/python3.10/inspect.py'>
      msg = 'Email Account admin not found'
      raise_exception = <class 'frappe.exceptions.DoesNotExistError'>
      strip_html_tags = <function strip_html_tags at 0x7f07aed9edd0>
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
      inspect = <module 'inspect' from '/usr/lib/python3.10/inspect.py'>
      msg = 'Email Account admin not found'
      raise_exception = <class 'frappe.exceptions.DoesNotExistError'>
frappe.exceptions.DoesNotExistError: Email Account admin not found

**Comment by akurungadam** [comment]
> frappe.exceptions.DoesNotExistError: Email Account admin not found

Looks like a setup issue, please check your Email Account? thanks!

**Comment by deepakc21** [comment]
Hello @akurungadam just got this fixed. The option "email" is not visible because we need to set "Email" in Option of "Lab test" doctype. It will be then visible in the "receipient" table. I hope this procedure gets added in ERPnext documentation. 
![erp](https://user-images.githubusercontent.com/97949896/206625374-62c2a261-3605-4219-8ad9-6564ce8af398.png)
![erp1](https://user-images.githubusercontent.com/97949896/206625628-adbec4a6-acaf-43b1-a517-ca413d90bafa.png)

**Comment by akurungadam** [comment]
> I hope this procedure gets added in ERPnext documentation.

I've submitted an edit to the [documentation](https://docs.erpnext.com/docs/v13/user/manual/en/setting-up/notifications)
