### ISSUE TITLE
Inpatient status not updated in the patient encounter.

### ISSUE THREAD

**Issue by Anuradhapatiltacten** [earthians/marley#185]
The patient encounters have inpatient status. This will be updated only once.
When the inpatient status changes it is not updated.
 
![inpatient](https://user-images.githubusercontent.com/125440770/218967470-0e994315-14cc-4f1c-8888-0c720c4a4b94.png)

**Comment by akurungadam** [comment]
All the information available in a Patient Encounter is captured at the time of creation. Basically It's not meant to be updated, as it may be relevant to the assessment and plan recorded in the encounter. Maybe we'll add a description to the field for clarity.
