### ISSUE TITLE
Using "uninstall-app" does not remove "User Roles"

### ISSUE THREAD

**Issue by 0FiRE0** [earthians/marley#196]
## Context information (for bug reports)

**Output of `bench version`**
```
agriculture 0.0.1
erpnext 14.17.4
frappe 14.26.2
frappedesk 0.6.4
healthcare 0.0.1
hrms 15.0.0-dev
lms 0.0.1
payments 0.0.1
```

## Steps to reproduce the issue

1. Install an app to the site. E.g. `bench --site YOUR_SITE install-app healthcare`
2. Run migration. E.g. `bench --site YOUR_SITE migrate`
3. Uninstall the app. E.g. `bench --site YOUR_SITE uninstall-app healthcare`
4. Run migration again. E.g. `bench --site YOUR_SITE migrate`

### Observed result
The roles in the `User` settings are still showing up and can be selected.
Check the below screenshot, these are the roles available after uninstalling the `healthcare` app. (It is applicable as well for other apps, such as `LMS`)
![image](https://user-images.githubusercontent.com/19993814/222548738-946a926c-31ff-4dc3-8613-b7822c41430c.png)

### Expected result
The user roles should get deleted upon the un-installation process finishing.

### Stacktrace / full error message

```
No error log
```

## Additional information

Ubuntu 18.04.6 LTS `Frappe` install method: Docker Compose

**Comment by phot0n** [comment]
can be done via uninstall hooks (`after_uninstall`, `before_uninstall`) by the respective apps. transferring to health repo.

**Comment by akurungadam** [comment]
uninstall should be removing all app customisations after [this](https://github.com/frappe/health/pull/201), please report if you face any challenges. thanks!
