### ISSUE TITLE
Not having healthcare standard module

### ISSUE THREAD

**Issue by diana310895** [earthians/marley#23]
![imagen](https://user-images.githubusercontent.com/68945554/88776805-be7e6a00-d186-11ea-9d5b-df2e655a459c.png)

Hi,

I have been doing reports via Report Builder, but through this via, cannot be added columns with information about different document types.

So, I want to use standard reports types. When I open an standard report type (see the picture), I can add columns with information of different associated report types. What I have seen is that healthcare module does not have any standard report type. So, if you could make an standard report for patients would be excellent.

**Comment by akurungadam** [comment]
I guess [Patient History](https://docs.erpnext.com/docs/user/manual/en/healthcare/patient_history) as Rucha pointed out should have all care related information related to the Patient?

**Comment by ChillarAnand** [comment]
Patient history has all the required information of the patient. Users can add/remove specific items from patient history.

Feel free to re-open if you need any other details.
