### ISSUE TITLE
Cannot read properties of undefined in Healthcare Service Unit

### ISSUE THREAD

**Issue by hans-permana** [earthians/marley#234]
### Information about bug

Hi Frappe Healthcare Developers,

I have recently upgraded my Frappe to v14.38.3 and suddenly Healthcare Service Unit page is broken. The default tree view is not showing any data that I previously entered. Also, when clicking the button New, it shows the error below.

![frappe-healthcare-issue](https://github.com/frappe/health/assets/7643370/cab46941-eb0e-474b-a114-c692b4b0a734)

Anyone can shed some lights on this issue?

### Module

Setup / Configuration

### Version

ERPNext: v14.27.1 (HEAD)
Frappe Framework: v14.38.3 (HEAD)
Healthcare: v14.0.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
    at frappe.views.TreeView.prepare_fields (treeview.js:385:45)
    at frappe.views.TreeView.new_node (treeview.js:319:8)
    at HTMLButtonElement.<anonymous> (treeview.js:429:9)
    at HTMLButtonElement.<anonymous> (page.js:268:31)
    at HTMLButtonElement.dispatch (jquery.js:5430:27)
    at et.handle (jquery.js:5234:28)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akurungadam** [comment]
@hans-permana we have this [fixed](https://github.com/frappe/health/pull/214) on develop, will port this to the stable branch this week. Until then you can drive to the service unit list view and then switch to the tree view, this should work.

**Comment by akurungadam** [comment]
https://github.com/frappe/health/pull/250
