### ISSUE TITLE
Incorrect fetching of Lab Tests and Clinical Procedures from 'Healthcare Services' instead of 'Prescriptions' in Sales Invoice.

### ISSUE THREAD

**Issue by Irfan778899** [earthians/marley#258]
### Information about bug

Expected Behaviour:
When selecting 'Get Items' from 'Prescriptions' in the Sales Invoice, the Drug Prescription, Lab Tests and Clinical Procedures prescribed by the Healthcare practitioner during the Patient Encounter should be fetched. While selecting 'Get Items' from 'Healthcare Services' in the Sales Invoice, only the services that have been already provided to the patient should be fetched.

Actual Behaviour:
When selecting 'Get Items' from 'Healthcare Services' in the Sales Invoice, the system is currently fetching the Lab Tests and Clinical Procedures prescribed by the Healthcare practitioner during any Patient Encounter. If a patient does not opt for these prescribed tests and procedures, then these keep popping up in the get items from healthcare services all the time, which will be very confusing for billing users in the hospital. Hence this feature request.

Request for New Feature:
Upon submitting the Sales Invoice that includes Lab Tests and Clinical Procedures, there should be an automatic creation of these Lab Tests and Clinical Procedures, associated with the respective patient, to streamline the process and improve efficiency.

### Module

Outpatient Module

### Version

frappe 14.40.3
erpnext 14.30.6
healthcare 14.0.0

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gokul1407** [comment]
Hi @Irfan778899 is this issue resolved now?

**Comment by Irfan778899** [comment]
Hi @Gokul1407 the issue looks resolved.
