### ISSUE TITLE
HealthCare: Patient Name should be Customer's name

### ISSUE THREAD

**Issue by Helkyd** [earthians/marley#27]
As i have commented https://discuss.erpnext.com/t/erpnext-healthcare-merged-to-develop/28205/20
Also i have noticed that by default Administrator cannot delete the Patient record (correct) but don't see also the Status option to disable the record if the same is not correct.

I have created two Patients with same name and on the first the Customer name was the Patient record name and on the Second before creating the Patient i created the Customer in order to select it when creating the Patient .... But ended up with two Patients with same name and no option to disable the record with Customer name as Record number.

**Comment by ChillarAnand** [comment]
This is fixed in the latest versions.

When "John Doe" patient is created, a customer with name "John Doe" is created.

**Comment by ChillarAnand** [comment]
Closing this issue. Feel free to open if you are still facing the issue.
