### ISSUE TITLE
Healthcare - Customer Dashboard - Should have Healthcare related DocType

### ISSUE THREAD

**Issue by addymuliady** [earthians/marley#28]
Frappe/ERPNext 9.2.x

Healthcare Related DT such as Patient DT and maybe Consultation and Medical Record should appear on Dashboard and vice versa (Patient DT Dashboard should be linked to Customer Sales Invoice).

![image](https://user-images.githubusercontent.com/21187126/32119440-d09785b8-bb87-11e7-8383-30838b1f9cfc.png)

**Comment by akurungadam** [comment]
Patient link has been added to Sales Invoice since then, and all healthcare document links are part of the Patient dashboard. Closing this considering that Linked DocTypes are configurable in latest version.
