### ISSUE TITLE
Patient Appointment: The mode of payment set in show payment dialog is not set in SI

### ISSUE THREAD

**Issue by Irfan778899** [earthians/marley#289]
### Information about bug

Actual behaviour:
After the Patient Appointment is booked ,  "Enter Payment Details" dialog box appears, if we set the mode of payment in that dialog box and  click on "Create Invoice" button, that mode of payment is not getting reflected in the "Payments" section of Sales Invoice which is generated.

Expected behaviour:
After the Patient Appointment is booked , the mode of payment set in  "Enter Payment Details" dialog box should be reflected in the "Payments" section of Sales Invoice which is generated.

### Module

Outpatient Module

### Version

Frappe version - 14.51.0
ERPNext version - 14.41.1
Frappe Health version - 14.0.2

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sajinsr** [comment]
Thank you for reaching out to us and bringing the issue you encountered in Frappe Health to our attention. We appreciate your diligence in reporting it. We will keep you updated on the progress and resolution of this issue.
