### ISSUE TITLE
For different Patients, view 'Patient History' is same

### ISSUE THREAD

**Issue by Irfan778899** [earthians/marley#316]
### Information about bug

Expected Behaviour : When we open different Patients and view the Patient history,
it should show the history of particular Patient.

Actual Behaviour: When we open different Patients and view the Patient history,
it is showing the same Patient history for all the Patients

https://github.com/frappe/health/assets/127736908/dc82f9a0-d533-4027-9074-091f3bc10cef

### Module

Outpatient Module

### Version

Frappe version - 14.53.0
ERPNext version - 14.44.1
Frappe Health version - 14.0.2

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vamagithub** [comment]
##  PR:    #357
