### ISSUE TITLE
Patient DocType AutoName doesn't work

### ISSUE THREAD

**Issue by yashwantakashlal** [earthians/marley#335]
### Information about bug

Since there is an option to customize how we choose naming strategy for doctype, somehow for Patient DocType it is not getting honoured.

I am selecting Expression Type autoname strategy and using fields names there, but it is not working.

### Module

Setup / Configuration

### Version

Version - 14 for all

### Installation method

docker

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by akashkrishna619** [comment]
Just like Customer, supplier naming in Buying/Selling Settings, Patient Naming is chosen from Healthcare Settings  "Patient Name By".

**Comment by akashkrishna619** [comment]
@yashwantakashlal you can use Document Naming Rule.

**Comment by yashwantakashlal** [comment]
But I want to name the patients like first_name-mobile-### let's say. Basically, tied with field, that is not possible right then ?

**Comment by akashkrishna619** [comment]
Yes , create a Document Naming Rule for Patient and use `{first_name}.-.{mobile}.-.` inside Prefix field

**Comment by yashwantakashlal** [comment]
Understood, this works, thanks a lot @akashkrishna619

**Comment by yashwantakashlal** [comment]
Closing as i was able to make it work with the suggested solution.
