### ISSUE TITLE
Medication Request 

### ISSUE THREAD

**Issue by YOUSRISALLAM10** [earthians/marley#365]
### Information about bug

At Medication Request Not Linked item from Drug Code

### Module

Outpatient Module

### Version

ERPNext: v14.27.1 (version-14)

Frappe Health: v15.0.0-dev (develop)

Frappe Framework: v14.54.1 (version-14)

### Installation method

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akashkrishna619** [comment]
This issue has been fixed in the recent update
