### ISSUE TITLE
erpnext v10 Healthcare PATIENT RELATION should be unique 

### ISSUE THREAD

**Issue by fatheyabdelslam** [earthians/marley#39]
in erpnext Patient in child table PATIENT RELATION
i can add multi the same Relation which is not write
![image](https://user-images.githubusercontent.com/32373751/43267164-7e2cda94-90ed-11e8-9956-367aedbdfe13.png)

**Comment by ChillarAnand** [comment]
This is fixed in https://github.com/frappe/erpnext/commit/21983b8432f5175f2fe28f69c9d661acd22eedd2.

Closing this issue. Feel free to re-open if you are still facing it.
