### ISSUE TITLE
Patient Addresses

### ISSUE THREAD

**Issue by mafrica** [earthians/marley#41]
So as a newbie to Healthcare with ERPNext I am trying to feel my way forward.  I apologise if this ground is well trodden but I am struggling a little in trying to tap the right resources.

So my first issue is that I wish to attach a patient to a location (this is required for emergencies, transport planning and effectiveness studies).  I understand that there is a relationship between patient and customer (as used in the CRM world of ERPnext).  Here in Tanzania addresses are pretty loose at the street level and postcoding is in its infancy, but there is a fairly well defined hierarchy of region, district, ward, village.  I have a pretty well populated spreadsheet of this information with geolocation (lat/lon) information for the villages.

I read that many customers (roughly patient) can be associated with an address and many addresses with a customer and so I hope to be able to upload my data and as part of patient registration establish their village of residence - ensuring a reasonable level of accuracy eg there are many similar named villages in different districts and regions.

My testing to date seems to show that despite creation of a few addresses the customer form tells me that no addresses are added yet and that I should create a "new address" in essentially free form ie without verification of spelling or confirmation of eg district for a given village.

Can anyone make suggestions as to my best route forward?

**Comment by akurungadam** [comment]
Patient doctype can be linked in Address and Contact, and if required a custom field to set the geolocation should also help.
