### ISSUE TITLE
Error On Patient Dashboard

### ISSUE THREAD

**Issue by ernestoruiz89** [earthians/marley#431]
### Information about bug

I getting this error on patient > Panel Dasboard

![image](https://github.com/frappe/health/assets/1592496/2c973d0c-623f-48b7-b16e-6c6cfd5a5b1b)

I think is for this PR on ERPNext:

https://github.com/frappe/erpnext/pull/41106

### Module

Integration with ERPNext modules

### Version

Frappe - v15.21.2
ErpNext  - v15.24.1
Healthcare - v16.0.0-dev

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phalouvas** [comment]
The error is caused by the removal of heatmap in erpnext. The relevant commit is this: https://github.com/frappe/erpnext/commit/a8f03e8baa805bfa95aaaa55566d470d4de715e9
