### ISSUE TITLE
Import Error While accessing the Dashboard Tab in Patient Doctype

### ISSUE THREAD

**Issue by maniamartial** [earthians/marley#475]
### Information about bug

Users can easily access the Patient doctype, but when they click on the Dashboard tab, an unclear error message (server error) related to an import issue pops up every time.

![image](https://github.com/frappe/health/assets/60258622/5c770a06-1a84-4f76-bceb-fb2e0f2f9807)

### Module

Patient History

### Version

Frappe Health: v15.0.0

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
To enhance the user experience and avoid confusion, the application should display a clear and informative message explaining what actions the user needs to take to avoid encountering these errors.

The current issue appears to be related to an import error, which might be due to a change in the name or structure within the ERPNxext app where the relevant function is defined. Ensuring the function names and references are consistent across the application will help resolve this issue.

Implementing these changes will guide users more effectively and prevent the errors from occurring, leading to a smoother and more intuitive user experience.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sajinsr** [comment]
Hi @maniamartial This issue has been resolved
