### ISSUE TITLE
healthcare is not available in ERPNext

### ISSUE THREAD

**Issue by landryjohn** [earthians/marley#49]
After the successful installation of ERPNext. And the activation of all modules. I don't see the healthcare module in the modules. How to make it visible please. I have already checked that it is enabled in "Domain Settings". But it is not always visible.

**Comment by ChillarAnand** [comment]
@landryjohn Once ERPNext is installed, you need to install healthcare app separately. You can find the instructions at https://github.com/frappe/healthcare/pull/50/files

**Comment by landryjohn** [comment]
Thank !!! It works.
