### ISSUE TITLE
Healthcare Practitioner list doesn't fetch in any form

### ISSUE THREAD

**Issue by HackerDyn** [earthians/marley#74]
Hi Guys, 

I have encountered one issue in Healthcare practitioner. eventhough I have created the master entries for practitioners with all time schedules, the practitioners data is not fetching in any linked forms. for example in patient appointment form etc. seems like the get_practitioner_list is having some issue. I have seen a similar issue here. https://github.com/frappe/erpnext/issues/16638
but its too old and the code has been changed ever since. hope the team will look into it..  really appreciate all your helps and support. 

![Untitled1](https://user-images.githubusercontent.com/6417545/61852752-44f4d180-aecb-11e9-9206-86de21abef49.png)

**Comment by ChillarAnand** [comment]
@Freshdigits This issue is fixed in the latest version of Frappe Health.

Feel free to re-open if you still face issue after upgrading the app.
